### ISSUE TITLE
Are generated samples available?

### ISSUE THREAD

**Issue by impredicative** [nstockton/speechlight#9]
Are samples available to listen to for the TTS and screen reader? This is the most important thing for any such software.

**Comment by nstockton** [comment]
Hello, thank you for your question, and your interest in the library.

There aren't any speech samples, and samples of speech would be out of scope for this library.

This library does not generate speech its self. It is rather a wrapper around existing APIs for screen readers used by blind people such as [NVDA,](https://www.nvaccess.org "NVDA Official Site") [JAWS,](https://www.freedomscientific.com/products/software/jaws "JAWS Official Site") [System Access,](https://www.satogo.com/en "System Access Official Site") and [VoiceOver.](https://www.apple.com/accessibility/vision "VoiceOver Official Site") It also has basic support for [Microsoft Speech API](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ms723627(v=vs.85) "MS SAPI Official Site") using the same interface, but if a person only wants to output to SAPI, there are better solutions for that.

Each one of these products has a different API. Some require the use of a dynamically linked library, some use OS specific APIs such as Windows COM. The purpose of the library is to provide a single, lightweight interface that is consistent across all the supported products, in order to make it easier for a developer who simply wants to output messages via a blind user's screen reader, without implementing support for a bunch of different screen reader APIs. Each of these products support multiple text to speech engines, and have different default voices. This library makes no attempt to talk to the text to speech engines directly, it just sends the text to a screen reader if one is running, or MS SAPI if on Windows and a supported screen reader was not detected. Any speech samples would thus be demoing the end text to speech engine that the screen reader is currently using, not the screen reader, and not this library.
